services:
  - type: web
    name: shambhu-sense
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn student_predictor.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

